#!/usr/bin/python3
"""
This module is designed to factorize numbers as much as possible.
"""
import sys
import time


def is_prime(n):
    """
    This function checks if n is a prime number.

    Args:
        n (int): The input number to test.

    Returns:
        True if n is a prime number, False otherwise.
    """
    if n < 2:
        return False
    if n == 2:
        return True
    for i in range(2, int(n / 2) + 1):
        if n % i == 0:
            return False
    return True


def factorize(n):
    """
    This function returns the factors of a given number.

    Args:
        n (int): The input number to factorize.

    Returns:
        The factors of the number.
    """
    factors = []
    for k in range(2, int(n / 2) + 1):
        if n % k == 0:
            b = k
            c = int(n / k)
            if is_prime(c) and is_prime(b):
                factors.append(c)
                factors.append(b)
                return factors
    return None


def main():
    """
    The main function.

    Raises:
        FileNotFoundError: If the file does not exist.
    """
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        exit()
    try:
        file = open(sys.argv[1], "r")
        numbers = file.readlines()
        for number in numbers:
            number = int(number)
            start_time = time.time()
            factors = factorize(number)
            if factors is None:
                print(f"{number} is a prime number.")
            else:
                print(f"{number}={factors[0]}*{factors[1]}")
            if time.time() - start_time > 5:
                exit("Out of time.")
    except FileNotFoundError:
        print(f"Error: '{sys.argv[1]}' does not exist.")


if __name__ == "__main__":
    main()
